basePath: /
consumes:
- application/json
info:
  title: API
  version: '1.0'
paths:
- - - /api/admin/dashboard
    - get:
        operationId: get_admin_dashboard_resource
        responses:
          '200':
            description: Success
        summary: Get admin dashboard statistics
        tags:
        - default
  - - /api/admin/export
    - get:
        operationId: get_export_user_stats_resource
        responses:
          '200':
            description: Success
        summary: Check status of the export or download a specific file
        tags:
        - default
      post:
        operationId: post_export_user_stats_resource
        responses:
          '200':
            description: Success
        summary: Trigger asynchronous CSV generation of user statistics
        tags:
        - default
  - - /api/admin/users
    - get:
        operationId: get_admin_users_resource
        responses:
          '200':
            description: Success
        summary: Get list of users with their statistics
        tags:
        - default
  - - /api/chapters
    - delete:
        operationId: delete_chapter_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      get:
        operationId: get_chapter_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      patch:
        operationId: patch_chapter_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      post:
        operationId: post_chapter_resources
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/check_token_valid
    - get:
        description: 'Keyword arguments:

          argument -- description

          Return: return_description'
        operationId: get_check_token_valid_resource
        responses:
          '200':
            description: Success
        summary: returns role of the user
        tags:
        - default
      post:
        operationId: post_check_token_valid_resource
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/dashboard
    - get:
        operationId: get_user_dashboard_resource
        responses:
          '200':
            description: Success
        summary: 'Return quizzes categorized into two parts: upcoming quizzes and
          past quizzes'
        tags:
        - default
  - - /api/fetchQuestions
    - get:
        description: 'Expects a query parameter `quiz_id`.

          Keyword arguments:

          argument -- description

          Return: return_description'
        operationId: get_take_quiz_resource
        responses:
          '200':
            description: Success
        summary: return the quiz_id, number of questions, time duration, and time
          of day for the quiz, question_id, question, options, marks
        tags:
        - default
  - - /api/login
    - get:
        operationId: get_user_login_resource
        responses:
          '200':
            description: Success
        tags:
        - default
      post:
        operationId: post_user_login_resource
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/logout
    - post:
        operationId: post_user_logout_resource
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/questions
    - delete:
        operationId: delete_question_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      get:
        operationId: get_question_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      post:
        operationId: post_question_resources
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/quizzes
    - delete:
        description: Expects a JSON body with the quiz_id to delete.
        operationId: delete_quiz_resources
        responses:
          '200':
            description: Success
        summary: Delete a quiz by its ID
        tags:
        - default
      get:
        description: If subject_id is 9999, return all quizzes.
        operationId: get_quiz_resources
        responses:
          '200':
            description: Success
        summary: Return quizzes based on subject_id
        tags:
        - default
      post:
        description: |
          {
            "title": "hello",
            "remarks": "jhvjhv",
            "timeduration": "1",
            "date": "2025-07-15",
            "subject_id": 2,
            "chapter_id": 2,
            "time_of_day": "12:00:00"
          }
        operationId: post_quiz_resources
        responses:
          '200':
            description: Success
        summary: 'Create a new quiz with the following JSON structure:'
        tags:
        - default
  - - /api/register
    - post:
        operationId: post_user_register_resource
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/scoreboard
    - get:
        operationId: get_return_users_score_board
        responses:
          '200':
            description: Success
        summary: Return the user's score board with detailed scores for each quiz
        tags:
        - default
  - - /api/scores
    - get:
        operationId: get_scores_resource
        responses:
          '200':
            description: Success
        summary: return all the scores of the user
        tags:
        - default
  - - /api/subjects
    - delete:
        operationId: delete_subject_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      get:
        operationId: get_subject_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      patch:
        operationId: patch_subject_resources
        responses:
          '200':
            description: Success
        tags:
        - default
      post:
        operationId: post_subject_resources
        responses:
          '200':
            description: Success
        tags:
        - default
  - - /api/takeResponse
    - post:
        description: Expects a JSON body with quiz_id, question_id, and selected_option.
        operationId: post_take_response_resource
        responses:
          '200':
            description: Success
        summary: Submit the quiz responses and calculate the score
        tags:
        - default
  - - /api/test
    - get:
        operationId: get_test_post_resource
        responses:
          '200':
            description: Success
        tags:
        - default
      post:
        operationId: post_test_post_resource
        responses:
          '200':
            description: Success
        tags:
        - default
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags:
- description: Default namespace
  name: default